### ISSUE TITLE
Needed Features list

### ISSUE THREAD

**Issue by IrealiTY** [IrealiTY/crc-bot#1]
- Welcome message to new users

- Users messaging in a channel a command `.iam`  for example `.iam Tank` gives the user a Tank class
- Which role can be used with this command must be set first with the command ".asar" (".asar Tank" done by an admin,  allows the users to do .iam tank - roles not prior assigned by .asar can not be used for .iam)
- The bot also keeps the channel where users have to use the command clean (deletes the user's command and the bot reply (you have been assigned the role....)  after a few seconds)
- we have monitoring channel, where the bot is literally tracking everything on the server. just an example:
```
:clock5:【11:50:57】 Message :pencil: #general
:bust_in_silhouette:Radical User#6606
        Old: xxxxx
        New: xxxxxyyyy

:clock5:【11:51:42】 New Message #general
:bust_in_silhouette:User#5665 xxxxx
```
track everything basically

- make the bot available to the `.iam` command via PM (we have tons of users messaging the bot instead of using the command in the #announcements channel)
- slow mode for a channel (1 message every 1 hour allowed)

- `.iamnot` command to allow users to remove themselves from a role
- purge configured channels of all messages at a specific time each day

**Comment by GeekyDeaks** [comment]
Is it ok to put most of the configurable stuff in a static .json file to start with?  This means we don't need some way of storing the config (i.e. DB or module to update config.js), nor do we have to implement the config commands.

This will probably mean the roles, welcome message and slow threshold for the moment.

**Comment by GeekyDeaks** [comment]
Does the `.iam` command toggle the role?

**Comment by GeekyDeaks** [comment]
Do you want the `.iam` command to *always* respond via PM and only clean up the request and response if it's in a guild channel?
