### ISSUE TITLE
travis-CI integration

### ISSUE THREAD

**Issue by GeekyDeaks** [IrealiTY/crc-bot#2]
Hi Aleks,

I'd like to link the project to travis for the test framework.  Would you be able to link your github account with travis here: https://travis-ci.org/auth and then go the profile page on travis and enable the crc-bot repo?

Cheers,
Scott

**Comment by IrealiTY** [comment]
set and done

**Comment by GeekyDeaks** [comment]
cheers! that seems to be working perfectly!
