### ISSUE TITLE
self assigned roles

### ISSUE THREAD

**Issue by GeekyDeaks** [IrealiTY/crc-bot#3]
I would like to detail the required behaviour of the `iam` and `iamnot` commands if possible.

- should the commands self delete in both PM and guild channels?
- if the member executes the same command twice, should it error or simply report that the command was successful (it just did not have to do anything)
- do the roles need to be mapped or are they *exactly* the same name as the discord roles? - if we keep them mapped, then we can remove any case-sensitivity in the command and still work if someone enters in `.iam cASterS`
- do you want the response messages to be configurable?

**Comment by GeekyDeaks** [comment]
Actually I forgot about something regarding PMs - the bot can only delete it's own message - so it might be prudent to just leave everything as is in a PM

**Comment by IrealiTY** [comment]
>should the commands self-delete in both PM and guild channels?

yep

>if the member executes the same command twice, should it error or simply report that the command was successful (it just did not have to do anything)

hm....I think the best would be just to let it pass as a success (what's your take on it?)

>do the roles need to be mapped or are they exactly the same name as the discord roles? - if we keep them mapped, then we can remove any case-sensitivity in the command and still work if someone enters in .iam cASterS

if that's an option that would be great we have  a lot of ... "special users" that cant spell

>do you want the response messages to be configurable?

No need for that, the bot can just replay "you were assigned the role X"

**Comment by GeekyDeaks** [comment]
I have checked and the bot cannot remove messages from the user in a PM.  For the moment I have coded it to only delete the messages if they are in a server/guild channel.
