### ISSUE TITLE
message throttle

### ISSUE THREAD

**Issue by GeekyDeaks** [IrealiTY/crc-bot#5]
I would like to clarify how you want the message throttle (slow mode) to operate:

- Is the 1 message per hour just per user, or per user per channel?
- Are there any roles/users to be excluded from the throttling?
- Is the throttle on *all* guild channels or specific ones?

**Comment by IrealiTY** [comment]
We have 2 channels #LFG and #LFM we'd like to throttle them IF needed individually.
All users all affected 1 message per hour per user per channel.
(only during peak hours not always on)

**Comment by GeekyDeaks** [comment]
hmmm... ok, so how about this:

> The rate limiting automatically turns on if the number of postings in the channel exceeds a specified rate. e.g. 100 messages per hour.  The rate limit then turns off after a specified delay (e.g. 2 hours) or if the *attempts* at messages falls below a specified value.

What do you think?

**Comment by IrealiTY** [comment]
That sounds perfect

**Comment by GeekyDeaks** [comment]
Ok, as a simple solution I'm going to implement a token bucket and see how well it works.  We can maybe start with a bucket size of 5 tokens with a refill rate of 1 token per hour.  This will allow users to burst up to 5 messages before they hit the rate limit and have to wait for their bucket to be refilled.

https://en.wikipedia.org/wiki/Token_bucket
